language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 361458/react-test -f ./client/Dockerfile.dev ./client

# use previous build to run multiple scripts
script:
  - docker run -e CI=true 361458/react-test npm test

after_success:
  - docker build -t 361458/multi-client ./client
  - docker build -t 361458/multi-nginx ./nginx
  - docker build -t 361458/multi-server ./server
  - docker build -t 361458/multi-worker ./worker

# log in to the docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take those images and push them to docker hub
- docker push 361458/multi-client
- docker push 361458/multi-nginx
- docker push 361458/multi-server
- docker push 361458/multi-worker